### ISSUE TITLE
installation instructions unclear

### ISSUE THREAD

**Issue by dfaure-kdab** [kurkale6ka/zsh#6]
I don't need your full zsh setup, just to try fuzzy cd ;)
Following the instructions in README.md, it wasn't clear how to use the git checkout. I finally found out that I had to copy autoload/fuzzy from the git checkout to ~/.config/zsh/autoload/fuzzy.

It would also be convenient if XDG_CONFIG_HOME and XDG_DATA_HOME were allowed to be unset, and the default values were used automatically. My own setup would unset those after they were set by the snippet you provided, leading to more setup trouble.

Finally, I get some errors when using 'c' and selecting a locate result:
c:51: bad math expression: operand expected at `/d/kde/src...'

I'm also wondering if the locate results are supposed to include files (as they currently do) instead of just directories? I guess it's useful when looking for a file, but in my case, it makes the selection huge when I'm looking for a directory (whose name also exists in many files).

Thanks for trying to develop a working autojump replacement, it's useful ;)

**Comment by dfaure-kdab** [comment]
You could also mention that only the fzf binary is necessary, which is easier than getting all of fzf from git.

**Comment by kurkale6ka** [comment]
Close via 5a9e54deebcece53f723b8efc15096bfbe8409e8 and 560741d7b75742c3949f062b014c183d2c75559f

**Comment by dfaure-kdab** [comment]
Not really, the next user will still have no clear instruction saying that he's supposed to copy autoload/fuzzy (and just that, the rest is unrelated) to ~/.config/zsh/autoload/fuzzy.

**Comment by kurkale6ka** [comment]
You just have to put those 3 functions in your autoload directory and that is clear from the README. You don't have to follow the folder structure that I used and also it is never suggested that you copy anything else from my zsh setup :-)
