### ISSUE TITLE
substring matches only?

### ISSUE THREAD

**Issue by dfaure-kdab** [kurkale6ka/zsh#7]
When I do `c kmail`, it offers me
* a directory called kmail (great)
* the path kde/pim/akonadiconsole, which matches k.*m.*a.*i.*l by pure chance, it can't possibly be what I have in mind when typing kmail :)

Can "c" be configured to only offer substring matches? At least when there actually are substring matches?

**Comment by kurkale6ka** [comment]
Hi,

The fuzzy matching is done by fzf, nothing to do with `c`. With fzf, if you want to match whole words you need to prefix them with a quote (`'`) but please read the docs for more info

**Comment by dfaure-kdab** [comment]
Well, `c` could call `fzf` with the single-quote prefix, so that one doesn't have to type `c \'kmail` (not really convenient)

**Comment by kurkale6ka** [comment]
I am not going to impose non fuzzy matching by default. As I suggested, please read the docs:
https://github.com/junegunn/fzf#search-syntax
you could simply use: `export FZF_DEFAULT_OPTS=-e` plus the backslash can be omitted once fzf has started: so `c` alone then `'`
